import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.ensemble import RandomForestRegressor

st.set_page_config(page_title="FormuAI-QbD", layout="wide")

# Header Section
st.title("💊 FormuAI-QbD")
st.caption("An Explainable AI Platform for Tablet Formulation Strategy & Virtual Performance Prediction")
st.warning("⚠️ Scientific Disclaimer: Virtual recommendations and machine-learning predictions generated by this platform are for decision-support only and require future laboratory validation.")

# Load Rules Data
@st.cache_data
def load_data():
    try:
        df = pd.read_csv("drug_rules.csv")
    except Exception as e:
        # Fallback dataset if file is missing or renamed
        df = pd.DataFrame({
            "Drug_Name": ["Metformin", "Paracetamol", "Amlodipine", "Omeprazole"],
            "Half_Life_hrs": [6.0, 2.5, 30.0, 1.0],
            "BCS_Class": ["Class I", "Class III", "Class I", "Class II"],
            "Swallowing_Difficulty": ["No", "Yes", "No", "No"],
            "Preferred_Onset": ["Prolonged", "Immediate", "Normal", "Delayed"],
            "Recommended_Tablet": ["Extended-Release Matrix", "Orally Disintegrating (ODT)", "Immediate-Release", "Enteric-Coated Tablet"],
            "Excipient_Strategy": ["HPMC K100M (20-40%)", "Mannitol, Crospovidone (5%)", "MCC, Starch", "Eudragit L100-55"],
            "Critical_Quality_Attribute": ["Release at 12h", "Disintegration <30s", "Dissolution >85%", "Acid Resistance"],
            "Key_Risk": ["Burst release", "High friability", "Moisture degradation", "Gastric degradation"]
        })
    return df

df_rules = load_data()

# Navigation Bar
tabs = st.sidebar.radio("Navigation Menu", [
    "1. Home & Overview",
    "2. Formulation Strategy Advisor",
    "3. Performance Predictor (ML)",
    "4. Release Kinetics Engine",
    "5. QbD Risk & Report Generator"
])

# TAB 1: HOME
if tabs == "1. Home & Overview":
    st.header("Project Overview")
    st.write("FormuAI-QbD assists formulation scientists and pharmacy researchers in selecting tablet dosage forms, predicting dissolution performance, and structuring Quality-by-Design (QbD) parameters.")
    
    st.markdown("""
    *Core System Architecture:*
    1. *Formulation Strategy Advisor:* Rule-based decision engine mapping drug properties to target tablet types.
    2. *Performance Predictor:* Machine Learning model estimating disintegration times and 12-hour drug release percentages.
    3. *Release Kinetics Engine:* Kinetic model fitting for Zero-Order, First-Order, and Korsmeyer-Peppas kinetics.
    4. *QbD Risk Matrix:* Automated generation of Quality Target Product Profiles (QTPP) and Critical Quality Attributes (CQAs).
    """)

# TAB 2: STRATEGY ADVISOR
elif tabs == "2. Formulation Strategy Advisor":
    st.header("Formulation Strategy Advisor")
    
    drug_list = list(df_rules["Drug_Name"].unique()) + ["Other / Custom Drug"]
    selected_drug = st.selectbox("Select Active Pharmaceutical Ingredient (API):", drug_list)
    
    if selected_drug != "Other / Custom Drug":
        drug_info = df_rules[df_rules["Drug_Name"] == selected_drug].iloc[0]
        half_life = st.number_input("Half-Life (hours):", value=float(drug_info["Half_Life_hrs"]))
        bcs = st.selectbox("BCS Class:", ["Class I", "Class II", "Class III", "Class IV"], index=["Class I", "Class II", "Class III", "Class IV"].index(drug_info["BCS_Class"]))
        swallowing = st.selectbox("Swallowing Difficulty?", ["No", "Yes"], index=0 if drug_info["Swallowing_Difficulty"]=="No" else 1)
        onset = st.selectbox("Target Onset/Action:", ["Immediate", "Normal", "Prolonged", "Delayed"], index=["Immediate", "Normal", "Prolonged", "Delayed"].index(drug_info["Preferred_Onset"]))
    else:
        half_life = st.number_input("Half-Life (hours):", value=4.0)
        bcs = st.selectbox("BCS Class:", ["Class I", "Class II", "Class III", "Class IV"])
        swallowing = st.selectbox("Swallowing Difficulty?", ["No", "Yes"])
        onset = st.selectbox("Target Onset/Action:", ["Immediate", "Normal", "Prolonged", "Delayed"])
    
    if st.button("Generate Strategy Recommendation"):
        rec_tablet = "Immediate-Release Tablet"
        excipients = "Binder (PVP K30), Diluent (MCC), Disintegrant (SSG)"
        cqa = "Disintegration & Dissolution Rate"
        risk = "Poor bioavailability if drug solubility is low"
        
        if swallowing == "Yes":
            rec_tablet = "Orally Disintegrating Tablet (ODT)"
            excipients = "Superdisintegrant (Crospovidone 5-10%), Soluble Diluent (Mannitol)"
            cqa = "Disintegration Time (<30 seconds)"
            risk = "High tablet friability"
        elif onset == "Prolonged" or half_life < 4.0:
            rec_tablet = "Extended-Release Hydrophilic Matrix Tablet"
            excipients = "Matrix Polymer (HPMC K100M 20-40%), Binder (MCC)"
            cqa = "12-hour Drug Release Profile"
            risk = "Dose dumping or incomplete drug release"
        elif onset == "Delayed" or bcs == "Class II":
            rec_tablet = "Enteric-Coated Tablet"
            excipients = "Enteric Polymer (Eudragit L100-55), Plasticizer (TEC)"
            cqa = "Acid Resistance in 0.1N HCl for 2 hours"
            risk = "Premature release in gastric pH"
            
        st.success(f"*Recommended Strategy:* {rec_tablet}")
        st.info(f"*Excipient Strategy:* {excipients}")
        st.write(f"*Critical Quality Attribute (CQA):* {cqa}")
        st.warning(f"*Key Risk to Monitor:* {risk}")

# TAB 3: PERFORMANCE PREDICTOR
elif tabs == "3. Performance Predictor (ML)":
    st.header("Formulation Performance Predictor")
    st.write("Predict disintegration time and 12-hour release using virtual machine learning models.")
    
    col1, col2 = st.columns(2)
    with col1:
        polymer = st.slider("Polymer Percentage (%)", 0, 50, 20)
        binder = st.slider("Binder Percentage (%)", 1, 10, 3)
    with col2:
        disintegrant = st.slider("Disintegrant Percentage (%)", 0, 15, 4)
        tablet_wt = st.number_input("Target Tablet Weight (mg)", value=300)
        
    # Synthetic ML Model Execution
    np.random.seed(42)
    X_train = np.random.uniform(low=[0,1,0,100], high=[50,10,15,500], size=(100,4))
    y_disint = X_train[:,0]*0.5 + X_train[:,1]*0.2 - X_train[:,2]*0.8 + np.random.normal(0,1,100)
    y_release = 100 - (X_train[:,0]*1.2) + (X_train[:,2]*0.5)
    
    model_dis = RandomForestRegressor().fit(X_train, y_disint)
    model_rel = RandomForestRegressor().fit(X_train, y_release)
    
    pred_d = max(0.5, model_dis.predict([[polymer, binder, disintegrant, tablet_wt]])[0])
    pred_r = min(100.0, max(0.0, model_rel.predict([[polymer, binder, disintegrant, tablet_wt]])[0]))
    
    st.metric("Predicted Disintegration Time", f"{pred_d:.2f} mins")
    st.metric("Predicted 12-Hour Cumulative Release", f"{pred_r:.2f} %")

# TAB 4: RELEASE KINETICS
elif tabs == "4. Release Kinetics Engine":
    st.header("Release Kinetics Fitting")
    
    time_input = st.text_input("Enter Time Points (hours, comma separated):", "1, 2, 4, 6, 8, 12")
    release_input = st.text_input("Enter % Cumulative Release (comma separated):", "12, 25, 48, 65, 78, 92")
    
    try:
        t = np.array([float(x.strip()) for x in time_input.split(",")])
        r = np.array([float(x.strip()) for x in release_input.split(",")])
        
        fig = px.line(x=t, y=r, markers=True, labels={'x':'Time (hours)', 'y':'% Release'}, title="In-Vitro Dissolution Profile")
        st.plotly_chart(fig)
        
        r2_zero = round(np.corrcoef(t, r)[0,1]**2, 3)
        r2_first = round(np.corrcoef(t, np.log(100 - r + 1e-5))[0,1]**2, 3)
        
        st.write(f"*Zero-Order Fit ($R^2$):* {r2_zero}")
        st.write(f"*First-Order Fit ($R^2$):* {r2_first}")
    except:
        st.error("Please enter valid comma-separated numeric values.")

# TAB 5: QBD REPORT
elif tabs == "5. QbD Risk & Report Generator":
    st.header("Quality by Design (QbD) Risk Assessment")
    
    qbd_data = pd.DataFrame({
        "QbD Element": ["QTPP", "CQA", "CMA", "CPP"],
        "Parameter": ["Controlled oral delivery", "Dissolution rate & Hardness", "Polymer viscosity & particle size", "Compression force & blending time"],
        "Target Specification": ["80-90% release at 12h", ">85% in 30 mins / 5-8 kg/cm2", "Standardized grade (e.g. K100M)", "Optimal hardness without capping"]
    })
    
    st.table(qbd_data)
    st.download_button("Download QbD Summary (CSV)", qbd_data.to_csv(index=False), "QbD_Summary.csv", "text/csv")